inherit_from:
  - https://raw.githubusercontent.com/omu/omu/master/etc/rubocop/rubocop.yml
  - https://raw.githubusercontent.com/omu/omu/master/etc/rubocop/rubocop-performance.yml
  - https://raw.githubusercontent.com/omu/omu/master/etc/rubocop/rubocop-minitest.yml

Layout/SpaceAroundMethodCallOperator:
  Enabled: false

Naming/FileName:
  Exclude:
    - 'lib/omu-support.rb'

AllCops:
  TargetRubyVersion: 2.5
