# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in support.gemspec
gemspec

gem 'minitest', '~> 5.0'
gem 'rake', '~> 13.0'
gem 'rubocop', '~> 1.3.0'
gem 'rubocop-minitest', require: false
gem 'rubocop-performance', require: false
gem 'rubocop-rake', require: false
