name: Ruby

on: [push,pull_request]

jobs:
  support-test:
    runs-on: ubuntu-latest
    env:
      support-directory: ./support
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5.0
    - name: Run the default task
      working-directory: ${{env.support-directory}}
      run: |
        gem install bundler -v 2.2.0
        bundle install
        bundle exec rake
      