name: Support

on:
  push:
    paths:
      - 'support/**'

jobs:
  support-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.5', '2.7', '3.0']
    env:
      support-directory: ./support
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Run the default task
      working-directory: ${{env.support-directory}}
      run: |
        bundle exec rake
